### PR TITLE
colour rewrite: add hsl/husl support

### LINKED ISSUE #13: rewrite colour support
I found a HuSL implementation in your code, but it is currently not accessible from CartoCSS. Additionally, HSL colour definitions are not supported yet.
Maybe it would be beneficial to rewrite colour support to some generic colour type, which is converted to RGB(A) at the end. Compare https://github.com/mapbox/carto/pull/422, where I defined colours internally as HSLA including a flag if we are in perceptual space or not.

I tried to implement HSLA support, but got stuck at https://github.com/omniscale/magnacarto/blob/2537d1e3e227114cd09b6817c81b6a61accefadc/builder/mapnik/serialize.go#L580. My Go knowledge is not good enough to figure out how to input some more generic type to this function and do the necessary adjustments within. Maybe you have a hint.

Another thing: it might be better to move the HuSL implementation to some external library.

### PR DESCRIPTION
**Pull request by nebulon42**
Fixes #13.

Adds support for HSL/HSLA and HUSL/HUSLA, moves husl implementation to external library.
Adds missing colour functions that carto supports like greyscale, hue, saturation, lightness, alpha.

The implementation has the following characteristics:
- the colour object knows if it is a perceptual colour or not
- internally colours are no longer represented in rgb but in hsl (or husl) values
- colour functions like lighten, darken operate on the respective colour space (internally they only manipulate hsl or husl values)
- there are lightenp, darkenp, ... functions to force a colour into perceptual colour space
- hue, saturation, ... always return the value of the (converted) non-perceptual colour
- huep, saturationp, ... always return the value of the (converted) perceptual colour
- the mix function operates on perceptual colours if there is at least one perceptual colour in its parameters
- chained colour functions operate on the HSL or HUSL space as long as possible, the conversion to rgb or rgba is done at the end

The similarity of HSL and HUSL in terms of values keeps the representation simple. The perceptual colour space is kind of sticky. Once you are in it is difficult to get out again, but I thought this would be no problem.

HUSL is not yet supported by carto, but there is a corresponding PR (https://github.com/mapbox/carto/pull/422).

### CODE REVIEW

**Comment by olt** [comment]
Thanks a lot, this looks really great.
Just for clarification, this is fully backwards compatible right? As the lighten & co. functions already use HSL.

**Comment by nebulon42** [comment]
Yes, it should be. The only thing that can happen are small rounding errors from RGB input to RGB output since it now transitions via HSL internally. If you look at the test in https://github.com/omniscale/magnacarto/blob/master/color/color_test.go#L27-L30 you see that it is still passing, so it should not be a big problem.

**Comment by olt** [comment]
I needed to fix quoting for mapserver output. There are no tests for that, except the regression tests.

I also reverted the rgbToHsl and hslToRgb implementations to my version. Otherwise we would have to add the full license text from chorme.js. The old implementation rounded the hue values to integers, which resulted in small rounding errors when converting back and forth. I fixed that and all tests pass. Maybe that was your reason to change the implementation?

However, all changes are rebased and merged Thanks a lot for this patch!

**Comment by nebulon42** [comment]
TBH I don't remember exactly. But that may have been the reason. Anyway, fine for me. Thanks for merging!

**Pull request closed without merging**
